// Universal buy-intent tags a buyer can attach to a buy request, plus
// category-specific tags. These help sellers filter and find suitable posts
// without reading every single one.
// Values are stored as the `en` key; localizeBuyRequestTag() maps back to the
// active language for display.

export const BUY_REQUEST_TAGS = [
  { en: "Urgent", ar: "عاجل" },
  { en: "New only", ar: "جديد فقط" },
  { en: "Used ok", ar: "مستعمل مقبول" },
  { en: "With warranty", ar: "مع ضمان" },
  { en: "Delivery", ar: "توصيل" },
  { en: "Pickup", ar: "استلام" },
  { en: "Gift", ar: "هدية" },
];

export const BUY_REQUEST_CATEGORY_TAGS = {
  electronics: [
    { en: "Charger included", ar: "مع الشاحن" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Unlocked", ar: "مفتوح لكل الشبكات" },
    { en: "Sealed", ar: "مختوم" },
  ],
  cars: [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
  ],
  furniture: [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Disassembly available", ar: "تفكيك متاح" },
    { en: "Washable covers", ar: "أغطية قابلة للغسل" },
    { en: "Well maintained", ar: "معتنى به" },
  ],
  fashion: [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "From clean closet", ar: "من خزانة نظيفة" },
  ],
  realestate: [
    { en: "Furnished", ar: "مفروش" },
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "Available now", ar: "متاح الآن" },
  ],
  services: [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Mobile service", ar: "خدمة متنقلة" },
    { en: "Materials included", ar: "شامل المواد" },
  ],
  toys: [
    { en: "All pieces", ar: "كل القطع" },
    { en: "Original packaging", ar: "بالتغليف الأصلي" },
    { en: "Complete set", ar: "طقم كامل" },
    { en: "Age-appropriate", ar: "مناسب للعمر" },
  ],
  sports: [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Carry bag included", ar: "حقيبة حمل مشمولة" },
  ],
  books: [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Hardcover", ar: "غلاف مقوّى" },
    { en: "Complete set", ar: "مجموعة كاملة" },
  ],
  animals: [
    { en: "Vaccinated", ar: "مطعّم" },
    { en: "Trained", ar: "مدرّب" },
    { en: "Healthy", ar: "سليم" },
    { en: "With supplies", ar: "مع المستلزمات" },
  ],
  jobs: [
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "Visa provided", ar: "إقامة مشمولة" },
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
  ],
  education: [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "One-on-one", ar: "خصوصي" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
  ],
  occasions: [
    { en: "All-inclusive", ar: "شامل الكل" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
  ],
  antiques: [
    { en: "Authentic", ar: "أصلي" },
    { en: "With certificate", ar: "مع شهادة" },
    { en: "Rare", ar: "نادر" },
    { en: "Appraised", ar: "مقيّم" },
  ],
  arts: [
    { en: "Signed", ar: "موقّع" },
    { en: "Framed", ar: "مؤطر" },
    { en: "Limited edition", ar: "إصدار محدود" },
    { en: "Handmade", ar: "صناعة يدوية" },
  ],
  families: [
    { en: "Fresh", ar: "طازج" },
    { en: "Family-made", ar: "منتج أسري" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Same-day prep", ar: "تحضير بنفس اليوم" },
  ],
  other: [
    { en: "Authentic", ar: "أصلي" },
    { en: "Working", ar: "شغّال" },
    { en: "Customizable", ar: "حسب الطلب" },
  ],
};

// Subcategory-specific tags, keyed by `${category}|${subcategoryEn}`.
// When a subcategory is selected, these take precedence over category tags.
export const BUY_REQUEST_SUBCATEGORY_TAGS = {
  // ===== FAMILIES =====
  "families|Food": [
    { en: "Fresh", ar: "طازج" },
    { en: "Frozen", ar: "مجمّد" },
    { en: "Homemade", ar: "صناعة منزلية" },
    { en: "Organic", ar: "عضوي" },
    { en: "Gluten-free", ar: "خالٍ من الغلوتين" },
    { en: "Vegetarian", ar: "نباتي" },
    { en: "Spicy", ar: "حار" },
    { en: "Family recipe", ar: "وصفة عائلية" },
  ],
  "families|Bakery & Sweets": [
    { en: "Fresh today", ar: "طازج اليوم" },
    { en: "Sugar-free", ar: "خالٍ من السكر" },
    { en: "Gluten-free", ar: "خالٍ من الغلوتين" },
    { en: "Custom design", ar: "تصميم حسب الطلب" },
    { en: "Mini size", ar: "حجم صغير" },
    { en: "Large tray", ar: "صينية كبيرة" },
    { en: "Gift box", ar: "علبة هدية" },
  ],
  "families|Handicrafts": [
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Traditional", ar: "تراثي" },
    { en: "One-of-a-kind", ar: "قطعة فريدة" },
    { en: "With gift wrap", ar: "مع تغليف هدية" },
  ],
  "families|Perfumes & Oud": [
    { en: "Original", ar: "أصلي" },
    { en: "Pure oud", ar: "عود خالص" },
    { en: "Alcohol-free", ar: "خالٍ من الكحول" },
    { en: "Long-lasting", ar: "ثبات طويل" },
    { en: "Custom blend", ar: "خلطة مخصصة" },
    { en: "Gift box", ar: "علبة هدية" },
    { en: "With burner", ar: "مع المبخرة" },
  ],
  "families|Clothing": [
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Embroidered", ar: "مطرّز" },
    { en: "Custom fit", ar: "تفصيل حسب الطلب" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
  ],
  "families|Natural Products": [
    { en: "Organic", ar: "عضوي" },
    { en: "Chemical-free", ar: "خالٍ من المواد الكيميائية" },
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Locally sourced", ar: "من مصدر محلي" },
    { en: "No preservatives", ar: "بلا مواد حافظة" },
    { en: "Family-made", ar: "منتج أسري" },
  ],

  // ===== ELECTRONICS =====
  "electronics|Phones": [
    { en: "Sealed", ar: "مختوم" },
    { en: "Unlocked", ar: "مفتوح لكل الشبكات" },
    { en: "With box", ar: "بالعلبة" },
    { en: "With charger", ar: "مع الشاحن" },
    { en: "With earphones", ar: "مع السماعات" },
    { en: "With case", ar: "مع الجراب" },
    { en: "Screen protector", ar: "حامي شاشة" },
    { en: "Battery > 90%", ar: "بطارية فوق ٩٠٪" },
    { en: "Dual SIM", ar: "ثنائي الشريحة" },
    { en: "Under warranty", ar: "تحت الضمان" },
  ],
  "electronics|Laptops": [
    { en: "With charger", ar: "مع الشاحن" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Under warranty", ar: "تحت الضمان" },
    { en: "SSD", ar: "SSD" },
    { en: "RAM upgraded", ar: "الرامات مرفوعة" },
    { en: "Touch screen", ar: "شاشة لمس" },
    { en: "Backlit keyboard", ar: "لوحة مفاتيح مضاءة" },
    { en: "Gaming GPU", ar: "كرت شاشة للألعاب" },
  ],
  "electronics|Tablets": [
    { en: "With charger", ar: "مع الشاحن" },
    { en: "With case", ar: "مع الجراب" },
    { en: "With keyboard", ar: "مع لوحة المفاتيح" },
    { en: "Screen protector", ar: "حامي شاشة" },
    { en: "Cellular model", ar: "يدعم شريحة" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
  ],
  "electronics|TVs & Screens": [
    { en: "With stand", ar: "مع القاعدة" },
    { en: "Wall mountable", ar: "قابل للتعليق" },
    { en: "With remote", ar: "مع الريموت" },
    { en: "Smart TV", ar: "تلفاز ذكي" },
    { en: "4K", ar: "4K" },
    { en: "OLED", ar: "OLED" },
    { en: "Curved", ar: "منحني" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
  ],
  "electronics|Audio": [
    { en: "Wireless", ar: "لاسلكي" },
    { en: "Noise cancelling", ar: "عزل الضوضاء" },
    { en: "Waterproof", ar: "مقاوم للماء" },
    { en: "With charging cable", ar: "مع كابل الشحن" },
    { en: "With case", ar: "مع الجراب" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Bass boost", ar: "صوت جهير" },
  ],
  "electronics|Gaming": [
    { en: "With controllers", ar: "مع أذرع التحكم" },
    { en: "With games", ar: "مع الألعاب" },
    { en: "Sealed", ar: "مختوم" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Disc edition", ar: "نسخة أقراص" },
    { en: "Digital edition", ar: "نسخة رقمية" },
    { en: "Extra storage", ar: "تخزين إضافي" },
    { en: "With headset", ar: "مع السماعة" },
  ],
  "electronics|Cameras & Photography": [
    { en: "With lens", ar: "مع العدسة" },
    { en: "DSLR", ar: "DSLR" },
    { en: "Mirrorless", ar: "بدون مرآة" },
    { en: "With bag", ar: "مع الحقيبة" },
    { en: "With strap", ar: "مع الحزام" },
    { en: "With memory card", ar: "مع كرت الذاكرة" },
    { en: "With tripod", ar: "مع الحامل" },
    { en: "Under warranty", ar: "تحت الضمان" },
  ],
  "electronics|Smart Watches & Wearables": [
    { en: "With charger", ar: "مع الشاحن" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "With straps", ar: "مع الأحزمة" },
    { en: "Sealed", ar: "مختوم" },
    { en: "Cellular model", ar: "يدعم شريحة" },
    { en: "GPS", ar: "GPS" },
    { en: "Heart rate monitor", ar: "مراقب نبض القلب" },
    { en: "Water resistant", ar: "مقاوم للماء" },
  ],
  "electronics|Computer Components": [
    { en: "Sealed", ar: "مختوم" },
    { en: "With warranty", ar: "مع ضمان" },
    { en: "Original", ar: "أصلي" },
    { en: "Compatible", ar: "متوافق" },
    { en: "DDR4", ar: "DDR4" },
    { en: "DDR5", ar: "DDR5" },
    { en: "NVMe", ar: "NVMe" },
    { en: "With cooler", ar: "مع المبرد" },
  ],
  "electronics|Accessories": [
    { en: "Original", ar: "أصلي" },
    { en: "Compatible", ar: "متوافق" },
    { en: "With packaging", ar: "بالتغليف" },
    { en: "Fast charging", ar: "شحن سريع" },
    { en: "Braided cable", ar: "كابل مجدول" },
    { en: "Universal fit", ar: "يناسب كل الأجهزة" },
  ],

  // ===== CARS =====
  "cars|Sedan": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "Automatic", ar: "أوتوماتيك" },
    { en: "Manual", ar: "عادي" },
    { en: "Sunroof", ar: "فتحة سقف" },
    { en: "Leather seats", ar: "جلد" },
    { en: "Navigation", ar: "نظام ملاحة" },
    { en: "Reverse camera", ar: "كاميرا خلفية" },
    { en: "Alloy wheels", ar: "جنوط" },
  ],
  "cars|SUV / 4x4": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "4WD", ar: "دفع رباعي" },
    { en: "Off-road ready", ar: "جاهز للطرق الوعرة" },
    { en: "Roof rack", ar: "حامل سقف" },
    { en: "Tow bar", ar: "كوش" },
    { en: "Third row seats", ar: "صف ثالث" },
    { en: "Leather seats", ar: "جلد" },
    { en: "Sunroof", ar: "فتحة سقف" },
  ],
  "cars|Hatchback": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "Fuel efficient", ar: "موفر للبنزين" },
    { en: "City car", ar: "سيارة مدينة" },
    { en: "Automatic", ar: "أوتوماتيك" },
    { en: "Manual", ar: "عادي" },
  ],
  "cars|Coupe": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "Sport mode", ar: "وضع رياضي" },
    { en: "Leather seats", ar: "جلد" },
    { en: "Sunroof", ar: "فتحة سقف" },
    { en: "Premium sound", ar: "نظام صوتي فاخر" },
  ],
  "cars|Sports Car": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "Sport exhaust", ar: "إكزوست رياضي" },
    { en: "Paddle shifters", ar: "نقل الحركة خلف الدركسيون" },
    { en: "Carbon trim", ar: "كاربون" },
    { en: "Premium brakes", ar: "فرامل رياضية" },
    { en: "Track-ready", ar: "جاهز للمضمار" },
  ],
  "cars|Convertible": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "Hard top", ar: "سقف صلب" },
    { en: "Soft top", ar: "سقف قماش" },
    { en: "Heated seats", ar: "تدفئة المقاعد" },
    { en: "Wind deflector", ar: "حاجب الريح" },
  ],
  "cars|Pickup Truck": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "4WD", ar: "دفع رباعي" },
    { en: "Tow package", ar: "عداد سحب" },
    { en: "Bed liner", ar: "بطانة الصندوق" },
    { en: "Tonneau cover", ar: "غطاء الصندوق" },
    { en: "Off-road ready", ar: "جاهز للطرق الوعرة" },
  ],
  "cars|Vans & Minivans": [
    { en: "GCC specs", ar: "مواصفات خليجية" },
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "7 seats", ar: "٧ ركاب" },
    { en: "8+ seats", ar: "٨ ركاب فأكثر" },
    { en: "Sliding doors", ar: "أبواب انزلاقية" },
    { en: "Captain chairs", ar: "مقاعد كابتن" },
    { en: "Family car", ar: "سيارة عائلية" },
  ],
  "cars|Motorcycles": [
    { en: "Low mileage", ar: "ممشور قليل" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Full service history", ar: "سجل صيانة كامل" },
    { en: "With helmet", ar: "مع الخوذة" },
    { en: "Sport bike", ar: "دراج رياضي" },
    { en: "Cruiser", ar: "كروزر" },
    { en: "Off-road", ar: "طرق وعرة" },
    { en: "ABS brakes", ar: "فرامل ABS" },
  ],
  "cars|Boats & Watercraft": [
    { en: "With trailer", ar: "مع المقطورة" },
    { en: "Low hours", ar: "ساعات تشغيل قليلة" },
    { en: "No accidents", ar: "بلا حوادث" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Engine included", ar: "مع المحرك" },
    { en: "GPS", ar: "GPS" },
    { en: "Fish finder", ar: "كاشف السمك" },
    { en: "Registered", ar: "مسجّل" },
    { en: "With cover", ar: "مع الغطاء" },
    { en: "Safety gear", ar: "معدات أمان" },
  ],
  "cars|Parts & Accessories": [
    { en: "Original OEM", ar: "قطع أصلية" },
    { en: "Aftermarket", ar: "بديل" },
    { en: "New", ar: "جديد" },
    { en: "Used", ar: "مستعمل" },
    { en: "With warranty", ar: "مع ضمان" },
    { en: "Compatible model", ar: "موديل متوافق" },
  ],

  // ===== FURNITURE =====
  "furniture|Sofas": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Washable covers", ar: "أغطية قابلة للغسل" },
    { en: "Recliner", ar: "مساند قابل للطي" },
    { en: "L-shaped", ar: "زاوية" },
    { en: "Corner sofa", ar: "كنبة زاوية" },
    { en: "3-seater", ar: "ثلاثي" },
    { en: "2-seater", ar: "ثنائي" },
    { en: "Disassembly available", ar: "تفكيك متاح" },
  ],
  "furniture|Beds": [
    { en: "With mattress", ar: "مع المرتبة" },
    { en: "Without mattress", ar: "بدون مرتبة" },
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Storage underneath", ar: "تخزين بالأسفل" },
    { en: "King size", ar: "كينج" },
    { en: "Queen size", ar: "كوين" },
    { en: "Single", ar: "فردي" },
    { en: "Bunk bed", ar: "سرير دورين" },
    { en: "Well maintained", ar: "معتنى به" },
  ],
  "furniture|Tables & Chairs": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Extendable", ar: "قابل للتمديد" },
    { en: "Folding", ar: "قابل للطي" },
    { en: "Glass top", ar: "سطح زجاج" },
    { en: "Marble top", ar: "سطح رخام" },
    { en: "Set of 6", ar: "طقم ٦ كراسي" },
    { en: "Set of 4", ar: "طقم ٤ كراسي" },
  ],
  "furniture|Storage": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Sliding doors", ar: "أبواب انزلاقية" },
    { en: "Adjustable shelves", ar: "رفوف قابلة للتعديل" },
    { en: "With mirror", ar: "مع مرآة" },
    { en: "Wardrobe", ar: "دولاب" },
    { en: "Bookshelf", ar: "مكتبة" },
    { en: "Chest of drawers", ar: "كومودينو" },
  ],
  "furniture|Decor": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Original", ar: "أصلي" },
    { en: "Wall art", ar: "لوحة جدارية" },
    { en: "Table lamp", ar: "أباجورة" },
    { en: "Rug", ar: "سجادة" },
    { en: "Vase", ar: "مزهرية" },
    { en: "Mirror", ar: "مرآة" },
  ],
  "furniture|Office Furniture": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Ergonomic", ar: "مريح طبيًا" },
    { en: "Adjustable height", ar: "ارتفاع قابل للتعديل" },
    { en: "Standing desk", ar: "مكتب وقوف" },
    { en: "Office chair", ar: "كرسي مكتبي" },
    { en: "Filing cabinet", ar: "خزنة ملفات" },
    { en: "Disassembly available", ar: "تفكيك متاح" },
  ],
  "furniture|Outdoor Furniture": [
    { en: "Weather resistant", ar: "مقاوم للطقس" },
    { en: "Rattan", ar: "خيزران" },
    { en: "Metal frame", ar: "هيكل معدني" },
    { en: "With cushions", ar: "مع الوسائد" },
    { en: "Stackable", ar: "قابل للتكديس" },
    { en: "Folding", ar: "قابل للطي" },
    { en: "UV resistant", ar: "مقاوم للشمس" },
    { en: "Well maintained", ar: "معتنى به" },
  ],
  "furniture|Kids Furniture": [
    { en: "Smoke-free", ar: "بيت بلا تدخين" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Safety certified", ar: "معتمد آمن" },
    { en: "Non-toxic paint", ar: "طلاء غير سام" },
    { en: "Rounded edges", ar: "حواف دائرية" },
    { en: "Adjustable height", ar: "ارتفاع قابل للتعديل" },
    { en: "Bunk bed", ar: "سرير دورين" },
  ],

  // ===== FASHION =====
  "fashion|Men": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "With receipt", ar: "مع الفاتورة" },
    { en: "Slim fit", ar: "قَصّ ضيق" },
    { en: "Regular fit", ar: "قَصّ عادي" },
    { en: "Large", ar: "حجم L" },
    { en: "Medium", ar: "حجم M" },
    { en: "Small", ar: "حجم S" },
  ],
  "fashion|Women": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "With receipt", ar: "مع الفاتورة" },
    { en: "Size XS", ar: "مقاس XS" },
    { en: "Size S", ar: "مقاس S" },
    { en: "Size M", ar: "مقاس M" },
    { en: "Size L", ar: "مقاس L" },
    { en: "Plus size", ar: "مقاس كبير" },
  ],
  "fashion|Kids": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "Age 2-4", ar: "عمر ٢-٤" },
    { en: "Age 5-8", ar: "عمر ٥-٨" },
    { en: "Age 9-12", ar: "عمر ٩-١٢" },
    { en: "Unisex", ar: "للجنسين" },
  ],
  "fashion|Shoes": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "With receipt", ar: "مع الفاتورة" },
    { en: "Size 39", ar: "مقاس ٣٩" },
    { en: "Size 40", ar: "مقاس ٤٠" },
    { en: "Size 41", ar: "مقاس ٤١" },
    { en: "Size 42", ar: "مقاس ٤٢" },
    { en: "Size 43", ar: "مقاس ٤٣" },
    { en: "Size 44", ar: "مقاس ٤٤" },
  ],
  "fashion|Bags": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "With dust bag", ar: "مع كيس الغبار" },
    { en: "With receipt", ar: "مع الفاتورة" },
    { en: "Leather", ar: "جلد" },
    { en: "Canvas", ar: "قماش" },
    { en: "Crossbody", ar: "كروسبودي" },
    { en: "Backpack", ar: "حقيبة ظهر" },
    { en: "Tote", ar: "توت" },
  ],
  "fashion|Watches": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "With papers", ar: "مع الأوراق" },
    { en: "Under warranty", ar: "تحت الضمان" },
    { en: "Automatic", ar: "أوتوماتيك" },
    { en: "Quartz", ar: "كوارتز" },
    { en: "Chronograph", ar: "كرونوغراف" },
    { en: "Water resistant", ar: "مقاوم للماء" },
    { en: "Sapphire crystal", ar: "زجاج ياقوتي" },
  ],
  "fashion|Jewelry": [
    { en: "Authentic", ar: "أصلي" },
    { en: "With certificate", ar: "مع شهادة" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Gold 18K", ar: "ذهب عيار ١٨" },
    { en: "Gold 21K", ar: "ذهب عيار ٢١" },
    { en: "Silver", ar: "فضة" },
    { en: "Diamond", ar: "ماس" },
    { en: "Pearl", ar: "لؤلؤ" },
    { en: "Unworn", ar: "غير ملبوس" },
  ],
  "fashion|Accessories": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original packaging", ar: "بالتغليف الأصلي" },
    { en: "Leather", ar: "جلد" },
    { en: "Belt", ar: "حزام" },
    { en: "Sunglasses", ar: "نظارات" },
    { en: "Scarf", ar: "وشاح" },
    { en: "Wallet", ar: "محفظة" },
    { en: "Hat", ar: "قبعة" },
  ],
  "fashion|Traditional Wear": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Embroidered", ar: "مطرّز" },
    { en: "Unworn", ar: "غير ملبوس" },
    { en: "Custom tailored", ar: "تفصيل خاص" },
    { en: "Original tags", ar: "بالعلامة الأصلية" },
    { en: "Abaya", ar: "عباية" },
    { en: "Thobe", ar: "ثوب" },
    { en: "Bisht", ar: "بشت" },
  ],

  // ===== REAL ESTATE =====
  "realestate|For Sale": [
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "Title deed ready", ar: "صك جاهز" },
    { en: "Vacant", ar: "فارغ" },
    { en: "Furnished", ar: "مفروش" },
    { en: "Unfurnished", ar: "غير مفروش" },
    { en: "Mortgage available", ar: "تمويل متاح" },
    { en: "Move-in ready", ar: "جاهز للسكن" },
  ],
  "realestate|For Rent": [
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "Bills included", ar: "الفواتير مشمولة" },
    { en: "Furnished", ar: "مفروش" },
    { en: "Unfurnished", ar: "غير مفروش" },
    { en: "Available now", ar: "متاح الآن" },
    { en: "Short term", ar: "إيجار قصير" },
    { en: "Long term", ar: "إيجار طويل" },
    { en: "Iqama required", ar: "يشترط إقامة" },
  ],
  "realestate|Apartments": [
    { en: "Upper floor", ar: "دور علوي" },
    { en: "Ground floor", ar: "دور أرضي" },
    { en: "Middle floor", ar: "دور متوسط" },
    { en: "With elevator", ar: "مع مصعد" },
    { en: "With parking", ar: "مع موقف" },
    { en: "With balcony", ar: "مع شرفة" },
    { en: "Furnished", ar: "مفروش" },
    { en: "Unfurnished", ar: "غير مفروش" },
    { en: "1 bedroom", ar: "غرفة نوم واحدة" },
    { en: "2 bedrooms", ar: "غرفتا نوم" },
    { en: "3+ bedrooms", ar: "٣ غرف نوم فأكثر" },
    { en: "With AC", ar: "مع مكيف" },
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
  ],
  "realestate|Villas": [
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "With garden", ar: "مع حديقة" },
    { en: "With pool", ar: "مع مسبح" },
    { en: "Furnished", ar: "مفروش" },
    { en: "Unfurnished", ar: "غير مفروش" },
    { en: "Driver room", ar: "غرفة سائق" },
    { en: "Maid room", ar: "غرفة عاملة" },
    { en: "Title deed ready", ar: "صك جاهز" },
    { en: "Gated community", ar: "مجمع مسوّر" },
  ],
  "realestate|Land": [
    { en: "Title deed ready", ar: "صك جاهز" },
    { en: "Residential", ar: "سكني" },
    { en: "Commercial", ar: "تجاري" },
    { en: "Corner plot", ar: "زاوية" },
    { en: "Main road", ar: "على شارع رئيسي" },
    { en: "Water connected", ar: "موصّل مياه" },
    { en: "Electricity connected", ar: "موصّل كهرباء" },
    { en: "Fenced", ar: "مسوّر" },
  ],
  "realestate|Commercial": [
    { en: "Direct owner", ar: "من المالك مباشرة" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "Street facing", ar: "على شارع" },
    { en: "With parking", ar: "مع موقف" },
    { en: "Office space", ar: "مكاتب" },
    { en: "Retail shop", ar: "محل تجاري" },
    { en: "Warehouse", ar: "مستودع" },
    { en: "Mezzanine", ar: "ميزانين" },
    { en: "Air conditioned", ar: "مكيّف" },
  ],
  "realestate|Shared Room": [
    { en: "Furnished", ar: "مفروش" },
    { en: "Bills included", ar: "الفواتير مشمولة" },
    { en: "Available now", ar: "متاح الآن" },
    { en: "No commission", ar: "بدون عمولة" },
    { en: "Single occupancy", ar: "إشغال فردي" },
    { en: "Shared bathroom", ar: "حمام مشترك" },
    { en: "With AC", ar: "مع مكيف" },
    { en: "Near metro", ar: "قرب المحطة" },
  ],

  // ===== SERVICES =====
  "services|Cleaning": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Deep clean", ar: "تنظيف عميق" },
    { en: "Move-out clean", ar: "تنظيف خروج" },
    { en: "Sofa cleaning", ar: "تنظيف كنب" },
    { en: "Carpet cleaning", ar: "تنظيف سجاد" },
    { en: "Window cleaning", ar: "تنظيف نوافذ" },
    { en: "Mobile service", ar: "خدمة متنقلة" },
    { en: "Eco-friendly", ar: "منتجات صديقة للبيئة" },
  ],
  "services|Maintenance": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "AC service", ar: "صيانة مكيفات" },
    { en: "Plumbing", ar: "سباكة" },
    { en: "Electrical", ar: "كهرباء" },
    { en: "Handyman", ar: "صلحات عامة" },
    { en: "With warranty", ar: "مع ضمان" },
    { en: "Emergency call", ar: "اتصال طوارئ" },
    { en: "Certified technician", ar: "فني معتمد" },
  ],
  "services|Tutoring": [
    { en: "Certified", ar: "معتمد" },
    { en: "One-on-one", ar: "خصوصي" },
    { en: "Group classes", ar: "مجموعات" },
    { en: "At home", ar: "في المنزل" },
    { en: "Online", ar: "أونلاين" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Exam prep", ar: "تجهيز للاختبارات" },
    { en: "Quran", ar: "قرآن" },
    { en: "Math", ar: "رياضيات" },
    { en: "English", ar: "إنجليزي" },
  ],
  "services|Transport": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Moving", ar: "نقل عفش" },
    { en: "Delivery", ar: "توصيل" },
    { en: "With packaging", ar: "مع التغليف" },
    { en: "Insurance included", ar: "تأمين مشمول" },
    { en: "Furniture moving", ar: "نقل أثاث" },
    { en: "Nationwide", ar: "لكل المملكة" },
  ],
  "services|Events": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "All-inclusive", ar: "شامل الكل" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Catering included", ar: "ضيافة مشمولة" },
    { en: "Decoration included", ar: "ديكور مشمول" },
    { en: "Indoor", ar: "داخلي" },
    { en: "Outdoor", ar: "خارجي" },
  ],
  "services|Beauty & Grooming": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Mobile service", ar: "خدمة متنقلة" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Home visit", ar: "زيارة منزلية" },
    { en: "Bridal", ar: "عروس" },
    { en: "Hair", ar: "شعر" },
    { en: "Makeup", ar: "مكياج" },
    { en: "Nails", ar: "أظافر" },
    { en: "Spa", ar: "سبا" },
    { en: "Men's grooming", ar: "حلاقة رجالي" },
    { en: "Henna", ar: "حناء" },
  ],
  "services|Health & Wellness": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Certified", ar: "معتمد" },
    { en: "Mobile service", ar: "خدمة متنقلة" },
    { en: "Home visit", ar: "زيارة منزلية" },
    { en: "Physiotherapy", ar: "علاج طبيعي" },
    { en: "Nutrition", ar: "تغذية" },
    { en: "Personal trainer", ar: "مدرب شخصي" },
    { en: "Massage", ar: "مساج" },
    { en: "Yoga", ar: "يوغا" },
  ],
  "services|IT & Tech Support": [
    { en: "Certified", ar: "معتمد" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "On-site", ar: "في الموقع" },
    { en: "Warranty", ar: "ضمان" },
    { en: "Data recovery", ar: "استرجاع بيانات" },
    { en: "Virus removal", ar: "إزالة فيروسات" },
    { en: "Network setup", ar: "تثبيت شبكة" },
  ],

  // ===== TOYS =====
  "toys|Kids Toys": [
    { en: "All pieces", ar: "كل القطع" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Age-appropriate", ar: "مناسب للعمر" },
    { en: "Battery operated", ar: "يعمل بالبطاريات" },
    { en: "Educational", ar: "تعليمي" },
    { en: "With remote", ar: "مع ريموت" },
    { en: "Original packaging", ar: "بالتغليف الأصلي" },
  ],
  "toys|Board Games": [
    { en: "All pieces", ar: "كل القطع" },
    { en: "Complete set", ar: "طقم كامل" },
    { en: "Good condition", ar: "بحالة جيدة" },
    { en: "2+ players", ar: "لاعبان فأكثر" },
    { en: "4+ players", ar: "٤ لاعبين فأكثر" },
    { en: "Family game", ar: "لعبة عائلية" },
    { en: "Strategy game", ar: "لعبة استراتيجية" },
    { en: "Party game", ar: "لعبة جماعية" },
  ],
  "toys|Collectibles": [
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Limited edition", ar: "إصدار محدود" },
    { en: "Mint condition", ar: "حالة ممتازة" },
    { en: "Rare", ar: "نادر" },
    { en: "Signed", ar: "موقّع" },
    { en: "First edition", ar: "طبعة أولى" },
    { en: "Vintage", ar: "كلاسيكي" },
    { en: "Sealed", ar: "مختوم" },
  ],
  "toys|Video Games": [
    { en: "All controllers", ar: "كل أذرع التحكم" },
    { en: "With games", ar: "مع الألعاب" },
    { en: "Sealed", ar: "مختوم" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Disc edition", ar: "نسخة أقراص" },
    { en: "Digital edition", ar: "نسخة رقمية" },
    { en: "Extra storage", ar: "تخزين إضافي" },
    { en: "With headset", ar: "مع السماعة" },
    { en: "4K ready", ar: "يدعم 4K" },
  ],
  "toys|Outdoor Toys": [
    { en: "All pieces", ar: "كل القطع" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Age-appropriate", ar: "مناسب للعمر" },
    { en: "Weather resistant", ar: "مقاوم للطقس" },
    { en: "With safety gear", ar: "مع معدات الأمان" },
    { en: "Inflatable", ar: "منفوخ" },
    { en: "Ride-on", ar: "ركوب" },
  ],
  "toys|Educational Toys": [
    { en: "All pieces", ar: "كل القطع" },
    { en: "Complete set", ar: "طقم كامل" },
    { en: "Age-appropriate", ar: "مناسب للعمر" },
    { en: "STEM", ar: "STEM" },
    { en: "Bilingual", ar: "ثنائي اللغة" },
    { en: "Interactive", ar: "تفاعلي" },
    { en: "Battery operated", ar: "يعمل بالبطاريات" },
  ],

  // ===== SPORTS =====
  "sports|Fitness": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Home gym", ar: "جيم منزلي" },
    { en: "Foldable", ar: "قابل للطي" },
    { en: "Adjustable weights", ar: "أوزان قابلة للتعديل" },
    { en: "With manual", ar: "مع الدليل" },
    { en: "Treadmill", ar: "جهاز مشي" },
    { en: "Dumbbells", ar: "دامبل" },
    { en: "Bench", ar: "بنش" },
  ],
  "sports|Bicycles": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "With helmet", ar: "مع الخوذة" },
    { en: "Mountain bike", ar: "دراج جبلي" },
    { en: "Road bike", ar: "دراج طرقي" },
    { en: "Folding", ar: "قابل للطي" },
    { en: "Electric", ar: "كهربائي" },
    { en: "Kids bike", ar: "دراج أطفال" },
    { en: "With lock", ar: "مع القفل" },
  ],
  "sports|Team Sports": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "With ball", ar: "مع الكرة" },
    { en: "Jersey", ar: "تيشيرت" },
    { en: "Shin guards", ar: "واقي الساق" },
    { en: "Football", ar: "كرة قدم" },
    { en: "Basketball", ar: "كرة سلة" },
    { en: "Volleyball", ar: "كرة طائرة" },
  ],
  "sports|Outdoor": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "With safety gear", ar: "مع معدات الأمان" },
    { en: "Camping", ar: "تخييم" },
    { en: "Hiking", ar: "مشي جبلي" },
    { en: "Fishing", ar: "صيد سمك" },
    { en: "With tent", ar: "مع الخيمة" },
    { en: "Waterproof", ar: "مقاوم للماء" },
  ],
  "sports|Water Sports": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "With safety gear", ar: "مع معدات الأمان" },
    { en: "Inflatable", ar: "منفوخ" },
    { en: "With pump", ar: "مع المضخة" },
    { en: "Surfboard", ar: "لوح ركوب" },
    { en: "Kayak", ar: "كاياك" },
    { en: "Life jacket", ar: "سترة نجاة" },
  ],
  "sports|Martial Arts": [
    { en: "All accessories", ar: "كل الملحقات" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "With safety gear", ar: "مع معدات الأمان" },
    { en: "Gi included", ar: "مع البزة" },
    { en: "Belt included", ar: "مع الحزام" },
    { en: "Training pads", ar: "وسائد تدريب" },
    { en: "Boxing gloves", ar: "قفازات ملاكمة" },
  ],

  // ===== BOOKS =====
  "books|Textbooks": [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Complete set", ar: "طقم كامل" },
    { en: "Latest edition", ar: "أحدث طبعة" },
    { en: "With CD", ar: "مع CD" },
    { en: "University level", ar: "مستوى جامعي" },
    { en: "High school", ar: "ثانوي" },
  ],
  "books|Novels": [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Paperback", ar: "غلاف ورقي" },
    { en: "Hardcover", ar: "غلاف مقوى" },
    { en: "First edition", ar: "طبعة أولى" },
    { en: "Signed", ar: "موقّع" },
    { en: "Bestseller", ar: "الأكثر مبيعًا" },
  ],
  "books|Religious": [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Hardcover", ar: "غلاف مقوى" },
    { en: "Tafsir", ar: "تفسير" },
    { en: "Hadith", ar: "حديث" },
    { en: "Fiqh", ar: "فقه" },
    { en: "Quran", ar: "قرآن" },
    { en: "With translation", ar: "مع ترجمة" },
  ],
  "books|Children": [
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "No tears", ar: "بلا تمزق" },
    { en: "Color illustrated", ar: "ملوّن" },
    { en: "Hardcover", ar: "غلاف مقوى" },
    { en: "Board book", ar: "كتاب مقوى" },
    { en: "Age 0-3", ar: "عمر ٠-٣" },
    { en: "Age 4-8", ar: "عمر ٤-٨" },
    { en: "Age 9-12", ar: "عمر ٩-١٢" },
  ],
  "books|Magazines": [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Complete set", ar: "مجموعة كاملة" },
    { en: "Back issue", ar: "عدد قديم" },
    { en: "Current issue", ar: "العدد الحالي" },
    { en: "Sealed", ar: "مختوم" },
  ],
  "books|Comics": [
    { en: "No highlights", ar: "بلا تظليل" },
    { en: "Clean pages", ar: "صفحات نظيفة" },
    { en: "Original packaging", ar: "بالتغليف الأصلي" },
    { en: "First edition", ar: "طبعة أولى" },
    { en: "Variant cover", ar: "غلاف بديل" },
    { en: "Complete series", ar: "سلسلة كاملة" },
    { en: "Graded", ar: "مصنّف" },
  ],

  // ===== ANIMALS =====
  "animals|Livestock": [
    { en: "Healthy", ar: "سليم" },
    { en: "Vaccinated", ar: "مطعّم" },
    { en: "With papers", ar: "مع الأوراق" },
    { en: "Grass-fed", ar: "يتغذى على العشب" },
    { en: "Goat", ar: "ماعز" },
    { en: "Sheep", ar: "خروف" },
    { en: "Cow", ar: "بقرة" },
    { en: "Camel", ar: "جمل" },
    { en: "For breeding", ar: "للتربية" },
  ],
  "animals|Pets": [
    { en: "Healthy", ar: "سليم" },
    { en: "Vaccinated", ar: "مطعّم" },
    { en: "Trained", ar: "مدرّب" },
    { en: "With supplies", ar: "مع المستلزمات" },
    { en: "Microchipped", ar: "بشريحة تعريف" },
    { en: "Sterilized", ar: "مخصي" },
    { en: "Vaccination card", ar: "بطاقة تطعيم" },
    { en: "Potty trained", ar: "مدرّب على الحمام" },
  ],
  "animals|Birds": [
    { en: "Healthy", ar: "سليم" },
    { en: "With cage", ar: "مع القفص" },
    { en: "Hand-tamed", ar: "أليف" },
    { en: "With supplies", ar: "مع المستلزمات" },
    { en: "Parrot", ar: "ببغاء" },
    { en: "Falcon", ar: "صقر" },
    { en: "Pigeon", ar: "حمام" },
    { en: "Singing bird", ar: "طائر مغرد" },
  ],
  "animals|Fish": [
    { en: "Healthy", ar: "سليم" },
    { en: "With tank", ar: "مع الحوض" },
    { en: "With filter", ar: "مع الفلتر" },
    { en: "Tropical", ar: "استوائي" },
    { en: "Freshwater", ar: "مياه عذبة" },
    { en: "Saltwater", ar: "مياه مالحة" },
    { en: "With supplies", ar: "مع المستلزمات" },
    { en: "Koi", ar: "كوي" },
    { en: "Goldfish", ar: "سمك ذهبي" },
  ],
  "animals|Reptiles": [
    { en: "Healthy", ar: "سليم" },
    { en: "With terrarium", ar: "مع الحوض الزجاجي" },
    { en: "Heat lamp included", ar: "مع مصباح حراري" },
    { en: "With supplies", ar: "مع المستلزمات" },
    { en: "Licensed", ar: "مرخّص" },
    { en: "Exotic", ar: "نادر" },
  ],
  "animals|Supplies": [
    { en: "New", ar: "جديد" },
    { en: "With packaging", ar: "بالتغليف" },
    { en: "Cage", ar: "قفص" },
    { en: "Aquarium", ar: "حوض أسماك" },
    { en: "Food", ar: "علف" },
    { en: "Bedding", ar: "فرشة" },
    { en: "Leash", ar: "حزام" },
    { en: "Carrier", ar: "حاملة" },
  ],

  // ===== JOBS =====
  "jobs|Full-time": [
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
    { en: "Visa provided", ar: "إقامة مشمولة" },
    { en: "Health insurance", ar: "تأمين طبي" },
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "Experience required", ar: "يشترط خبرة" },
    { en: "Fresh graduate ok", ar: "حديث تخرج مقبول" },
  ],
  "jobs|Part-time": [
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "Weekend only", ar: "ويكاند فقط" },
    { en: "Evening shift", ar: "دوام مسائي" },
    { en: "Student friendly", ar: "مناسب للطلاب" },
  ],
  "jobs|Freelance": [
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "Project-based", ar: "حسب المشروع" },
    { en: "Hourly rate", ar: "بالساعة" },
    { en: "Fixed price", ar: "سعر ثابت" },
    { en: "Portfolio required", ar: "يشترط معرض أعمال" },
  ],
  "jobs|Internship": [
    { en: "Remote ok", ar: "عن بُعد" },
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
    { en: "Paid", ar: "مدفوع" },
    { en: "Unpaid", ar: "تطوعي" },
    { en: "Certificate provided", ar: "شهادة معتمدة" },
    { en: "University credit", ar: "ساعات جامعية" },
  ],
  "jobs|Remote": [
    { en: "Immediate start", ar: "بدء فوري" },
    { en: "Flexible hours", ar: "ساعات مرنة" },
    { en: "Visa provided", ar: "إقامة مشمولة" },
    { en: "Anywhere in KSA", ar: "من أي مكان بالمملكة" },
    { en: "Global", ar: "دولي" },
    { en: "Async friendly", ar: "مرن زمنيًا" },
    { en: "Full-time", ar: "دوام كامل" },
    { en: "Part-time", ar: "دوام جزئي" },
  ],

  // ===== EDUCATION =====
  "education|Tutoring": [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "One-on-one", ar: "خصوصي" },
    { en: "Group classes", ar: "مجموعات" },
    { en: "At home", ar: "في المنزل" },
    { en: "Online", ar: "أونلاين" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Advanced", ar: "متقدم" },
    { en: "Exam prep", ar: "تجهيز للاختبارات" },
  ],
  "education|Courses": [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "Recorded sessions", ar: "جلسات مسجلة" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Advanced", ar: "متقدم" },
    { en: "Diploma", ar: "دبلوم" },
    { en: "Certificate", ar: "شهادة" },
    { en: "Professional", ar: "احترافي" },
  ],
  "education|Training": [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "Hands-on", ar: "تطبيقي" },
    { en: "Group classes", ar: "مجموعات" },
    { en: "Corporate", ar: "للشركات" },
    { en: "Individual", ar: "فردي" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Advanced", ar: "متقدم" },
  ],
  "education|Languages": [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "One-on-one", ar: "خصوصي" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Advanced", ar: "متقدم" },
    { en: "Conversation focus", ar: "تركيز على المحادثة" },
    { en: "Grammar focus", ar: "تركيز على القواعد" },
    { en: "IELTS prep", ar: "تجهيز IELTS" },
  ],
  "education|Online Classes": [
    { en: "Certified", ar: "معتمد" },
    { en: "Free trial", ar: "تجربة مجانية" },
    { en: "Recorded sessions", ar: "جلسات مسجلة" },
    { en: "Live sessions", ar: "جلسات مباشرة" },
    { en: "Beginner friendly", ar: "للمبتدئين" },
    { en: "Advanced", ar: "متقدم" },
    { en: "Self-paced", ar: "بإيقاع ذاتي" },
    { en: "Interactive", ar: "تفاعلي" },
  ],

  // ===== OCCASIONS =====
  "occasions|Weddings": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "All-inclusive", ar: "شامل الكل" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Henna", ar: "حناء" },
    { en: "Photography", ar: "تصوير" },
    { en: "Catering", ar: "ضيافة" },
    { en: "Decoration", ar: "ديكور" },
    { en: "Bridal", ar: "للعروس" },
  ],
  "occasions|Parties": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "All-inclusive", ar: "شامل الكل" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Birthday", ar: "عيد ميلاد" },
    { en: "Kids party", ar: "حفلة أطفال" },
    { en: "Corporate", ar: "للشركات" },
    { en: "Entertainment", ar: "ترفيه" },
  ],
  "occasions|Catering": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Buffet", ar: "بوفية" },
    { en: "Plated", ar: "أطباق" },
    { en: "Vegetarian options", ar: "خيارات نباتية" },
    { en: "Dessert included", ar: "حلى مشمول" },
    { en: "Service staff", ar: "طاقم خدمة" },
  ],
  "occasions|Rentals": [
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "Delivery included", ar: "توصيل مشمول" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Tables", ar: "طاولات" },
    { en: "Chairs", ar: "كراسي" },
    { en: "Tents", ar: "خيام" },
    { en: "Lighting", ar: "إضاءة" },
  ],
  "occasions|Decorations": [
    { en: "All-inclusive", ar: "شامل الكل" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "Setup included", ar: "تركيب مشمول" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Balloons", ar: "بالونات" },
    { en: "Flowers", ar: "ورود" },
    { en: "Lighting", ar: "إضاءة" },
    { en: "Stage", ar: "منصة" },
    { en: "Theme", ar: "ثيم" },
  ],
  "occasions|Photography": [
    { en: "Licensed", ar: "مرخّص" },
    { en: "Same-day", ar: "بنفس اليوم" },
    { en: "With album", ar: "مع الألبوم" },
    { en: "Available on date", ar: "متاح بالتاريخ" },
    { en: "Video included", ar: "فيديو مشمول" },
    { en: "Drone", ar: "درون" },
    { en: "Studio", ar: "استوديو" },
    { en: "Outdoor", ar: "خارجي" },
    { en: "Pre-wedding", ar: "قبل الزفاف" },
  ],

  // ===== ANTIQUES =====
  "antiques|Coins": [
    { en: "Authentic", ar: "أصلي" },
    { en: "With certificate", ar: "مع شهادة" },
    { en: "Rare", ar: "نادر" },
    { en: "Silver", ar: "فضة" },
    { en: "Gold", ar: "ذهب" },
    { en: "Historical", ar: "تاريخي" },
    { en: "Graded", ar: "مصنّف" },
    { en: "Sealed", ar: "مختوم" },
  ],
  "antiques|Heritage": [
    { en: "Authentic", ar: "أصلي" },
    { en: "With certificate", ar: "مع شهادة" },
    { en: "Rare", ar: "نادر" },
    { en: "Vintage", ar: "كلاسيكي" },
    { en: "Restored", ar: "مرمّم" },
    { en: "Original condition", ar: "حالة أصلية" },
    { en: "Handcrafted", ar: "صناعة يدوية" },
  ],
  "antiques|Collectibles": [
    { en: "Authentic", ar: "أصلي" },
    { en: "Original box", ar: "بالعلبة الأصلية" },
    { en: "Limited edition", ar: "إصدار محدود" },
    { en: "Mint condition", ar: "حالة ممتازة" },
    { en: "Rare", ar: "نادر" },
    { en: "Signed", ar: "موقّع" },
    { en: "Vintage", ar: "كلاسيكي" },
  ],
  "antiques|Antique Furniture": [
    { en: "Authentic", ar: "أصلي" },
    { en: "With certificate", ar: "مع شهادة" },
    { en: "Rare", ar: "نادر" },
    { en: "Well maintained", ar: "معتنى به" },
    { en: "Restored", ar: "مرمّم" },
    { en: "Original condition", ar: "حالة أصلية" },
    { en: "Handcrafted", ar: "صناعة يدوية" },
    { en: "Solid wood", ar: "خشب طبيعي" },
  ],

  // ===== ARTS =====
  "arts|Paintings": [
    { en: "Signed", ar: "موقّع" },
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Original", ar: "أصلي" },
    { en: "With frame", ar: "مع الإطار" },
    { en: "Limited edition", ar: "إصدار محدود" },
    { en: "Oil", ar: "زيت" },
    { en: "Acrylic", ar: "أكريليك" },
    { en: "Watercolor", ar: "ألوان مائية" },
  ],
  "arts|Handicrafts": [
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Original", ar: "أصلي" },
    { en: "One-of-a-kind", ar: "قطعة فريدة" },
    { en: "Traditional", ar: "تراثي" },
    { en: "Modern", ar: "عصري" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "With gift box", ar: "مع علبة هدية" },
  ],
  "arts|Calligraphy": [
    { en: "Signed", ar: "موقّع" },
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Original", ar: "أصلي" },
    { en: "Framed", ar: "مؤطر" },
    { en: "Custom name", ar: "اسم مخصص" },
    { en: "Traditional", ar: "تراثي" },
    { en: "Modern", ar: "عصري" },
    { en: "Gold leaf", ar: "ورق ذهبي" },
  ],
  "arts|Sculptures": [
    { en: "Signed", ar: "موقّع" },
    { en: "Handmade", ar: "صناعة يدوية" },
    { en: "Original", ar: "أصلي" },
    { en: "With base", ar: "مع القاعدة" },
    { en: "Bronze", ar: "برونز" },
    { en: "Stone", ar: "حجر" },
    { en: "Wood", ar: "خشب" },
    { en: "Limited edition", ar: "إصدار محدود" },
  ],
  "arts|Digital Art": [
    { en: "Original", ar: "أصلي" },
    { en: "Limited edition", ar: "إصدار محدود" },
    { en: "High resolution", ar: "دقة عالية" },
    { en: "Customizable", ar: "حسب الطلب" },
    { en: "NFT included", ar: "مع NFT" },
    { en: "Print included", ar: "طبعة مشمولة" },
    { en: "Digital download", ar: "تحميل رقمي" },
  ],
};

export function getBuyRequestTagsForCategory(category, subcategory) {
  const subs = Array.isArray(subcategory) ? subcategory : (subcategory ? [subcategory] : []);
  const tagMap = new Map();
  subs.forEach((sub) => {
    (BUY_REQUEST_SUBCATEGORY_TAGS[`${category}|${sub}`] || []).forEach((t) => tagMap.set(t.en, t));
  });
  if (tagMap.size > 0) return Array.from(tagMap.values());
  return BUY_REQUEST_CATEGORY_TAGS[category] || [];
}

export function localizeBuyRequestTag(value, lang) {
  const tag = BUY_REQUEST_TAGS.find((t) => t.en === value);
  if (tag) return lang === "ar" ? tag.ar : tag.en;
  for (const cat of Object.keys(BUY_REQUEST_CATEGORY_TAGS)) {
    const found = BUY_REQUEST_CATEGORY_TAGS[cat].find((t) => t.en === value);
    if (found) return lang === "ar" ? found.ar : found.en;
  }
  for (const key of Object.keys(BUY_REQUEST_SUBCATEGORY_TAGS)) {
    const found = BUY_REQUEST_SUBCATEGORY_TAGS[key].find((t) => t.en === value);
    if (found) return lang === "ar" ? found.ar : found.en;
  }
  return value;
}