import {
  LayoutGrid, Smartphone, Monitor, Gamepad2, Tv, Camera, Car, Bike, Truck,
  Wrench, Mountain, Building2, Armchair, ChefHat, Shirt, Watch, Sparkles, Baby,
  Dumbbell, Music, Book, Cat, Hammer, Store, Briefcase, Package, Home,
} from "lucide-react";
import { SAUDI_CITIES, getCityName, nearestCity } from "./countries";
export { SAUDI_CITIES, getCityName, nearestCity };

export const CATEGORIES = [
  { id: "all", en: "All", ar: "الكل", icon: LayoutGrid, color: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200" },
  { id: "phones", en: "Phones & Smart Devices", ar: "الجوالات والأجهزة الذكية", icon: Smartphone, color: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300" },
  { id: "computers", en: "Computers", ar: "الكمبيوترات", icon: Monitor, color: "bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300" },
  { id: "gaming", en: "Gaming", ar: "الألعاب والقيمنق", icon: Gamepad2, color: "bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300" },
  { id: "home_electronics", en: "Home Electronics", ar: "الإلكترونيات والترفيه المنزلي", icon: Tv, color: "bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300" },
  { id: "photography", en: "Photography & Content", ar: "التصوير وصناعة المحتوى", icon: Camera, color: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300" },
  { id: "cars", en: "Cars", ar: "السيارات", icon: Car, color: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300" },
  { id: "bikes_watercraft", en: "Bikes & Watercraft", ar: "الدراجات والمركبات البحرية", icon: Bike, color: "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300" },
  { id: "trucks", en: "Trucks & Heavy Vehicles", ar: "الشاحنات والمركبات الثقيلة", icon: Truck, color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300" },
  { id: "car_parts", en: "Car Parts & Accessories", ar: "قطع غيار وإكسسوارات السيارات", icon: Wrench, color: "bg-stone-100 text-stone-700 dark:bg-stone-800 dark:text-stone-200" },
  { id: "camping", en: "Camping & Outdoors", ar: "البر والتخييم والرحلات", icon: Mountain, color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" },
  { id: "realestate", en: "Real Estate", ar: "العقارات", icon: Building2, color: "bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-300" },
  { id: "furniture", en: "Furniture & Decor", ar: "الأثاث والديكور", icon: Armchair, color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300" },
  { id: "home_kitchen", en: "Home & Kitchen", ar: "المنزل والمطبخ", icon: ChefHat, color: "bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-300" },
  { id: "fashion", en: "Fashion & Clothing", ar: "الأزياء والملابس", icon: Shirt, color: "bg-pink-100 text-pink-700 dark:bg-pink-950 dark:text-pink-300" },
  { id: "watches_jewelry", en: "Watches, Jewelry & Gold", ar: "الساعات والمجوهرات والذهب", icon: Watch, color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-950 dark:text-yellow-300" },
  { id: "beauty", en: "Perfumes & Beauty", ar: "العطور والجمال والعناية الشخصية", icon: Sparkles, color: "bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-950 dark:text-fuchsia-300" },
  { id: "kids_babies", en: "Kids & Babies", ar: "الأطفال والمواليد", icon: Baby, color: "bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300" },
  { id: "sports", en: "Sports & Fitness", ar: "الرياضة واللياقة", icon: Dumbbell, color: "bg-lime-100 text-lime-700 dark:bg-lime-950 dark:text-lime-300" },
  { id: "music", en: "Music & Instruments", ar: "الموسيقى والآلات الموسيقية", icon: Music, color: "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300" },
  { id: "hobbies", en: "Hobbies & Collectibles", ar: "الهوايات والمقتنيات", icon: Book, color: "bg-stone-100 text-stone-700 dark:bg-stone-800 dark:text-stone-200" },
  { id: "animals", en: "Animals & Livestock", ar: "الحيوانات والفروسية والمواشي", icon: Cat, color: "bg-lime-100 text-lime-700 dark:bg-lime-950 dark:text-lime-300" },
  { id: "tools", en: "Tools & Equipment", ar: "الأدوات والمعدات", icon: Hammer, color: "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300" },
  { id: "business_equipment", en: "Business & Restaurant Equipment", ar: "معدات الأعمال والمطاعم والمشاريع", icon: Store, color: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200" },
  { id: "productive_families", en: "Productive Families", ar: "الأسر المنتجة", icon: Home, color: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300" },
  { id: "services", en: "Services", ar: "الخدمات", icon: Briefcase, color: "bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-300" },
  { id: "other", en: "Other", ar: "أخرى", icon: Package, color: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200" },
];

export const SUBCATEGORIES = {
  phones: [
    { en: "Phones", ar: "الجوالات" },
    { en: "Tablets", ar: "الأجهزة اللوحية" },
    { en: "Smart Watches", ar: "الساعات الذكية" },
    { en: "Fitness Bands & Trackers", ar: "أساور اللياقة وأجهزة التتبع" },
    { en: "Phone Accessories", ar: "إكسسوارات الجوال" },
    { en: "E-Readers", ar: "أجهزة القراءة الإلكترونية" },
    { en: "Smart Glasses", ar: "النظارات الذكية" },
    { en: "Wireless Earbuds (TWS)", ar: "السماعات اللاسلكية (TWS)" },
  ],
  computers: [
    { en: "Laptops", ar: "اللابتوبات" },
    { en: "Desktop PCs", ar: "أجهزة الكمبيوتر المكتبية" },
    { en: "Mini PCs", ar: "أجهزة Mini PC" },
    { en: "All-in-One PCs", ar: "أجهزة All-in-One" },
    { en: "Monitors", ar: "الشاشات" },
    { en: "Graphics Cards", ar: "كروت الشاشة" },
    { en: "Processors", ar: "المعالجات" },
    { en: "Motherboards", ar: "اللوحات الأم" },
    { en: "RAM", ar: "RAM" },
    { en: "Storage Drives", ar: "وحدات التخزين" },
    { en: "Power Supplies", ar: "مزودات الطاقة" },
    { en: "Cooling", ar: "التبريد" },
    { en: "PC Cases", ar: "صناديق الكمبيوتر" },
    { en: "Printers & Scanners", ar: "الطابعات والسكانرات" },
    { en: "Networking", ar: "أجهزة الشبكات" },
    { en: "Drawing Tablets", ar: "لوحات الرسم الرقمية" },
    { en: "Keyboards & Mice", ar: "لوحات المفاتيح والفأرة" },
    { en: "UPS Devices", ar: "أجهزة UPS" },
  ],
  gaming: [
    { en: "PlayStation", ar: "PlayStation" },
    { en: "Xbox", ar: "Xbox" },
    { en: "Nintendo", ar: "Nintendo" },
    { en: "Video Games", ar: "ألعاب الفيديو" },
    { en: "VR Headsets", ar: "أجهزة الواقع الافتراضي" },
    { en: "Controllers", ar: "أيدي التحكم" },
    { en: "Racing Wheels & Simulators", ar: "عجلات وأجهزة المحاكاة" },
    { en: "Gaming Headsets", ar: "Gaming Headsets" },
    { en: "Capture Cards", ar: "Capture Cards" },
    { en: "Gaming Chairs", ar: "Gaming Chairs" },
    { en: "Gaming Desks", ar: "Gaming Desks" },
    { en: "Game Cards & Credits", ar: "بطاقات الألعاب والشحن" },
  ],
  home_electronics: [
    { en: "TVs", ar: "التلفزيونات" },
    { en: "Projectors", ar: "أجهزة العرض" },
    { en: "Soundbars", ar: "Soundbars" },
    { en: "Home Theater Systems", ar: "أنظمة المسرح المنزلي" },
    { en: "Portable Speakers", ar: "السماعات المحمولة" },
    { en: "Headphones", ar: "سماعات الرأس" },
    { en: "Audio Systems", ar: "أجهزة الصوت" },
    { en: "Streaming Devices", ar: "أجهزة البث" },
  ],
  photography: [
    { en: "Cameras", ar: "الكاميرات" },
    { en: "Action Cameras", ar: "كاميرات الأكشن" },
    { en: "Cinema Cameras", ar: "كاميرات السينما" },
    { en: "Lenses", ar: "العدسات" },
    { en: "Drones", ar: "الطائرات بدون طيار" },
    { en: "Gimbals", ar: "Gimbals" },
    { en: "Lighting", ar: "الإضاءة" },
    { en: "Studio Equipment", ar: "معدات الاستوديو" },
    { en: "Podcast Equipment", ar: "معدات البودكاست" },
    { en: "Live Streaming Equipment", ar: "معدات البث المباشر" },
    { en: "Memory Cards & Readers", ar: "بطاقات الذاكرة وقارئاتها" },
    { en: "Camera Bags & Cases", ar: "حقائب وشنط الكاميرا" },
  ],
  cars: [
    { en: "Sedan", ar: "سيدان" },
    { en: "SUV", ar: "SUV" },
    { en: "Sports Cars", ar: "سيارات رياضية" },
    { en: "Luxury Cars", ar: "سيارات فاخرة" },
    { en: "Electric Cars", ar: "سيارات كهربائية" },
    { en: "Hybrid Cars", ar: "سيارات هجينة" },
    { en: "Classic Cars", ar: "سيارات كلاسيكية" },
    { en: "Pickup Trucks", ar: "بيك أب" },
    { en: "Vans", ar: "فان" },
    { en: "Hatchback", ar: "هاتشباك" },
    { en: "Caravans & RVs", ar: "كرفانات ومنازل متنقلة" },
    { en: "Golf Carts", ar: "عربات الجولف" },
  ],
  bikes_watercraft: [
    { en: "Motorcycles", ar: "الدراجات النارية" },
    { en: "Bicycles", ar: "الدراجات الهوائية" },
    { en: "Boats", ar: "القوارب" },
    { en: "Jet Skis", ar: "الجت سكي" },
    { en: "Trailers", ar: "المقطورات" },
    { en: "Electric Scooters", ar: "السكوترات الكهربائية" },
    { en: "ATVs & Buggies", ar: "الدبابات والباجي" },
  ],
  trucks: [
    { en: "Transport Trucks", ar: "شاحنات النقل" },
    { en: "Dump Trucks", ar: "القلابات" },
    { en: "Tow Trucks", ar: "السطحات" },
    { en: "Tankers", ar: "الصهاريج" },
    { en: "Refrigerated Trucks", ar: "شاحنات التبريد" },
    { en: "Truck Heads", ar: "رؤوس الشاحنات" },
    { en: "Heavy Trailers", ar: "المقطورات الثقيلة" },
    { en: "Cranes", ar: "الرافعات" },
    { en: "Buses", ar: "الحافلات" },
  ],
  car_parts: [
    { en: "Engines", ar: "المحركات" },
    { en: "Transmissions", ar: "القيرات" },
    { en: "Engine Parts", ar: "قطع المحرك" },
    { en: "Brakes", ar: "الفرامل" },
    { en: "Suspension", ar: "التعليق" },
    { en: "Tires", ar: "الإطارات" },
    { en: "Wheels", ar: "الجنوط" },
    { en: "Audio Systems", ar: "أنظمة الصوت" },
    { en: "Lighting", ar: "الإضاءة" },
    { en: "Car Cameras", ar: "كاميرات السيارات" },
    { en: "4x4 Accessories", ar: "إكسسوارات الدفع الرباعي" },
    { en: "Interior Accessories", ar: "إكسسوارات داخلية" },
    { en: "Batteries", ar: "البطاريات" },
    { en: "Oils & Fluids", ar: "الزيوت والسوائل" },
  ],
  camping: [
    { en: "Tents", ar: "الخيام" },
    { en: "Seating", ar: "الجلسات" },
    { en: "Cooking & Hospitality", ar: "الطبخ والضيافة" },
    { en: "Coolers & Fridges", ar: "الثلاجات والمبردات" },
    { en: "Generators", ar: "المولدات" },
    { en: "Power Stations & Batteries", ar: "محطات الطاقة والبطاريات" },
    { en: "Solar Power", ar: "الطاقة الشمسية" },
    { en: "الإنارة", ar: "الإنارة" },
    { en: "Trip Gear", ar: "معدات الرحلات" },
    { en: "Shades & Awnings", ar: "المظلات" },
    { en: "Fishing", ar: "الصيد" },
  ],
  realestate: [
    { en: "Apartments for Sale", ar: "شقق للبيع" },
    { en: "Apartments for Rent", ar: "شقق للإيجار" },
    { en: "Villas for Sale", ar: "فلل للبيع" },
    { en: "Villas for Rent", ar: "فلل للإيجار" },
    { en: "Floors", ar: "أدوار" },
    { en: "Annexes", ar: "ملاحق" },
    { en: "Traditional Houses", ar: "بيوت شعبية" },
    { en: "Residential Land", ar: "أراضي سكنية" },
    { en: "Commercial Land", ar: "أراضي تجارية" },
    { en: "Agricultural Land", ar: "أراضي زراعية" },
    { en: "Industrial Land", ar: "أراضي صناعية" },
    { en: "Residential Buildings", ar: "عمائر سكنية" },
    { en: "Commercial Buildings", ar: "عمائر تجارية" },
    { en: "Palaces", ar: "قصور" },
    { en: "Farms", ar: "مزارع" },
    { en: "Rest Houses", ar: "استراحات" },
    { en: "Chalets", ar: "شاليهات" },
    { en: "Offices", ar: "مكاتب" },
    { en: "Shops", ar: "محلات" },
    { en: "Warehouses", ar: "مستودعات" },
    { en: "Rooms for Rent", ar: "غرف للإيجار" },
  ],
  furniture: [
    { en: "Bedrooms", ar: "غرف النوم" },
    { en: "Majlis", ar: "المجالس" },
    { en: "Sofas", ar: "الكنب" },
    { en: "Tables", ar: "الطاولات" },
    { en: "Office Furniture", ar: "الأثاث المكتبي" },
    { en: "Carpets", ar: "السجاد" },
    { en: "Curtains", ar: "الستائر" },
    { en: "Decor", ar: "الديكور" },
    { en: "Outdoor & Garden Furniture", ar: "أثاث خارجي وحديقة" },
  ],
  home_kitchen: [
    { en: "Refrigerators", ar: "الثلاجات" },
    { en: "Washing Machines", ar: "الغسالات" },
    { en: "Dryers", ar: "النشافات" },
    { en: "Dishwashers", ar: "غسالات الصحون" },
    { en: "Ovens", ar: "الأفران" },
    { en: "ACs", ar: "المكيفات" },
    { en: "Vacuums", ar: "المكانس" },
    { en: "Coffee Machines", ar: "أجهزة القهوة" },
    { en: "Air Fryers", ar: "Air Fryers" },
    { en: "Blenders & Food Processors", ar: "الخلاطات ومحضرات الطعام" },
    { en: "Kitchen Tools", ar: "أدوات المطبخ" },
    { en: "Smart Home", ar: "Smart Home" },
    { en: "Tableware & Serving", ar: "أدوات المائدة والتقديم" },
    { en: "Water Heaters", ar: "سخانات المياه" },
    { en: "Water Filters & Purifiers", ar: "فلاتر ومنقيات المياه" },
  ],
  fashion: [
    { en: "Abayas", ar: "العبايات" },
    { en: "Men's Thobes", ar: "الثياب الرجالية" },
    { en: "Shemagh & Ghutra", ar: "الشماغ والغترة" },
    { en: "Bishts", ar: "البشوت" },
    { en: "Women's Clothing", ar: "الملابس النسائية" },
    { en: "Men's Clothing", ar: "الملابس الرجالية" },
    { en: "Sportswear", ar: "الملابس الرياضية" },
    { en: "Shoes", ar: "الأحذية" },
    { en: "Bags", ar: "الحقائب" },
    { en: "Accessories", ar: "الإكسسوارات" },
    { en: "Hijab & Scarves", ar: "الحجاب والطرح" },
    { en: "Maternity Wear", ar: "ملابس الحوامل" },
  ],
  watches_jewelry: [
    { en: "Luxury Watches", ar: "الساعات الفاخرة" },
    { en: "Smart Watches", ar: "الساعات الذكية" },
    { en: "Gold", ar: "الذهب" },
    { en: "Jewelry", ar: "المجوهرات" },
    { en: "Silver", ar: "الفضة" },
  ],
  beauty: [
    { en: "Perfumes", ar: "العطور" },
    { en: "Oud", ar: "العود" },
    { en: "Incense", ar: "البخور والدخون" },
    { en: "Makeup", ar: "المكياج" },
    { en: "Skincare", ar: "العناية بالبشرة" },
    { en: "Hair Care", ar: "العناية بالشعر" },
    { en: "Personal Care Devices", ar: "أجهزة العناية الشخصية" },
    { en: "Body Care", ar: "العناية بالجسم" },
  ],
  kids_babies: [
    { en: "Kids Toys", ar: "ألعاب الأطفال" },
    { en: "Strollers", ar: "عربات الأطفال" },
    { en: "Car Seats", ar: "كراسي السيارات" },
    { en: "Kids Furniture", ar: "أثاث الأطفال" },
    { en: "Baby Essentials", ar: "مستلزمات المواليد" },
    { en: "Kids Clothing", ar: "ملابس الأطفال" },
  ],
  sports: [
    { en: "Treadmills", ar: "أجهزة الجري" },
    { en: "Cardio Machines", ar: "أجهزة الكارديو" },
    { en: "Gym Equipment", ar: "أجهزة كمال الأجسام" },
    { en: "Weights", ar: "الأوزان" },
    { en: "Football", ar: "كرة القدم" },
    { en: "Basketball", ar: "كرة السلة" },
    { en: "Tennis", ar: "التنس" },
    { en: "Padel", ar: "البادل" },
    { en: "Swimming", ar: "السباحة" },
    { en: "Boxing", ar: "الملاكمة" },
    { en: "Golf", ar: "الغولف" },
    { en: "Volleyball", ar: "الكرة الطائرة" },
    { en: "Badminton", ar: "الريشة الطائرة" },
    { en: "Yoga & Pilates", ar: "اليوجا والبيلاتس" },
    { en: "Diving & Water Sports", ar: "الغوص والرياضات المائية" },
    { en: "Cricket", ar: "الكريكيت" },
    { en: "Archery", ar: "الرماية" },
  ],
  music: [
    { en: "Oud", ar: "العود" },
    { en: "Guitar", ar: "الجيتار" },
    { en: "Violin", ar: "الكمان" },
    { en: "Piano & Keyboard", ar: "البيانو والكيبورد" },
    { en: "Drums & Percussion", ar: "الطبول والإيقاع" },
    { en: "Wind Instruments", ar: "آلات النفخ" },
    { en: "Recording Equipment", ar: "معدات التسجيل" },
    { en: "DJ Equipment", ar: "معدات DJ" },
  ],
  hobbies: [
    { en: "Books", ar: "الكتب" },
    { en: "Coins", ar: "العملات" },
    { en: "Stamps", ar: "الطوابع" },
    { en: "Trading Cards", ar: "البطاقات" },
    { en: "Models & Figures", ar: "المجسمات" },
    { en: "Antiques & Artifacts", ar: "التحف" },
    { en: "Art", ar: "الفن" },
    { en: "Stationery & Office Supplies", ar: "القرطاسية والمستلزمات المكتبية" },
  ],
  animals: [
    { en: "Horses", ar: "الخيول" },
    { en: "Equestrian Supplies", ar: "مستلزمات الفروسية" },
    { en: "Camels", ar: "الإبل" },
    { en: "Sheep & Goats", ar: "الأغنام والماعز" },
    { en: "Cows", ar: "الأبقار" },
    { en: "Birds", ar: "الطيور" },
    { en: "Pets", ar: "الحيوانات الأليفة" },
    { en: "Animal Supplies", ar: "مستلزمات الحيوانات" },
    { en: "Cats", ar: "القطط" },
    { en: "Dogs", ar: "الكلاب" },
  ],
  tools: [
    { en: "Hand Tools", ar: "العدد اليدوية" },
    { en: "Power Tools", ar: "العدد الكهربائية" },
    { en: "Welding Equipment", ar: "معدات اللحام" },
    { en: "Workshop Equipment", ar: "معدات الورش" },
    { en: "Construction Equipment", ar: "معدات البناء" },
    { en: "Agricultural Equipment", ar: "المعدات الزراعية" },
  ],
  business_equipment: [
    { en: "Restaurant Equipment", ar: "معدات المطاعم" },
    { en: "Coffee Shop Equipment", ar: "معدات الكوفي" },
    { en: "Salon Equipment", ar: "معدات الصالونات" },
    { en: "Laundry Equipment", ar: "معدات المغاسل" },
    { en: "Shop Equipment", ar: "معدات المحلات" },
    { en: "Office Equipment", ar: "معدات المكاتب" },
    { en: "Complete Businesses", ar: "مشاريع كاملة" },
  ],
  productive_families: [
    { en: "Homemade Food", ar: "الأطعمة المنزلية" },
    { en: "Sweets & Pastries", ar: "الحلويات والمعجنات" },
    { en: "Baked Goods", ar: "المخبوزات" },
    { en: "Pickles & Preserves", ar: "المخللات والمربيات" },
    { en: "Spices & Seasonings", ar: "البهارات والنكهات" },
    { en: "Dairy & Cheese", ar: "الألبان والأجبان" },
    { en: "Honey & Natural Oils", ar: "العسل والزيوت الطبيعية" },
    { en: "Handicrafts", ar: "المشغولات اليدوية" },
    { en: "Sewing & Embroidery", ar: "الخياطة والتطريز" },
    { en: "Natural Cosmetics", ar: "العناية الطبيعية" },
    { en: "Handmade Gifts", ar: "الهدايا اليدوية" },
  ],
  services: [
    { en: "Car Services", ar: "خدمات السيارات" },
    { en: "Home Services", ar: "خدمات المنزل" },
    { en: "Tech Services", ar: "خدمات التقنية" },
    { en: "Education & Training", ar: "التعليم والتدريب" },
    { en: "Transport & Shipping", ar: "النقل والشحن" },
    { en: "Events", ar: "المناسبات" },
    { en: "Business Services", ar: "خدمات الأعمال" },
    { en: "Pet Services", ar: "خدمات الحيوانات الأليفة" },
    { en: "Home Care Services", ar: "خدمات الرعاية المنزلية" },
    { en: "Travel & Tourism", ar: "خدمات السياحة والسفر" },
  ],
  other: [
    { en: "Miscellaneous", ar: "متفرقات" },
    { en: "Tickets & Vouchers", ar: "تذاكر وقسائم" },
  ],
};

export function getSubcategories(catId) {
  return SUBCATEGORIES[catId] || [];
}

export const CONDITIONS = [
  { id: "new", en: "Brand New", ar: "جديد", color: "bg-emerald-500 text-white" },
  { id: "like_new", en: "Like New", ar: "كالجديد", color: "bg-teal-500 text-white" },
  { id: "excellent", en: "Excellent", ar: "ممتاز", color: "bg-blue-500 text-white" },
  { id: "good", en: "Good", ar: "جيد", color: "bg-cyan-500 text-white" },
  { id: "fair", en: "Fair", ar: "مقبول", color: "bg-amber-500 text-white" },
  { id: "poor", en: "Poor", ar: "ضعيف", color: "bg-orange-500 text-white" },
];

export function getCondition(id) {
  return CONDITIONS.find((c) => c.id === id) || (id === "used" ? CONDITIONS.find((c) => c.id === "good") : CONDITIONS[3]);
}

export function getCategory(id) {
  return CATEGORIES.find((c) => c.id === id) || CATEGORIES[0];
}

export const REPORT_REASONS = [
  { id: "not_available", en: "Listed as available but wasn't available", ar: "معلن كمتاح بس ما كان متوفر" },
  { id: "false_price", en: "False / misleading price tag", ar: "السعر المعروض غير صحيح" },
  { id: "counterfeit", en: "Counterfeit or fake item", ar: "منتج مقلد أو مزيف" },
  { id: "not_as_described", en: "Item not as described", ar: "غير مطابق للوصف" },
  { id: "prohibited", en: "Prohibited / banned item", ar: "منتج ممنوع" },
  { id: "scam", en: "Scam or fraud attempt", ar: "محاولة نصب أو احتيال" },
  { id: "inappropriate", en: "Inappropriate content", ar: "محتوى غير لائق" },
  { id: "harassment", en: "Harassment / abusive seller", ar: "مضايقة أو تعامل سيئ" },
  { id: "spam", en: "Spam / duplicate listing", ar: "إعلان مزعج أو مكرر" },
  { id: "other", en: "Other", ar: "سبب آخر" },
];